//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvProject.Models.Entity
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

    public partial class TblEgitimlerim
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Bu alaný boþ geçemezsiniz")]
        public string Baslik { get; set; }

		[Required(ErrorMessage = "Bu alaný boþ geçemezsiniz")]
	
		public string AltBaslik1 { get; set; }

		[Required(ErrorMessage = "Bu alaný boþ geçemezsiniz")]
		public string AltBaslik2 { get; set; }

		[Required(ErrorMessage = "Bu alaný boþ geçemezsiniz")]
		[StringLength(10,ErrorMessage="Lütfen en fazla 10 karakterlik veri giriþi yapýn")]
		public string GNO { get; set; }

		[Required(ErrorMessage = "Bu alaný boþ geçemezsiniz")]
		public string Tarih { get; set; }
    }
}
